spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: jdbc:sqlite:${SQLITE_FILE:./paopao.db}
  sql:
    init:
      platform: sqlite
mpQrCode: ${MP_QR_CODE} # 微信公众号链接
templateId: ${TEMPLATE_ID} # 消息模板id

wx:
  mp:
    app-id: ${WX_APP_ID} # 微信公众号appid
    secret: ${WX_SECRET}  # 微信公众号secret
log:
  path: /tmp