spring:
  profiles: prod
  datasource:
    url: ENC(+8YND7UMG8TSdynMtlwTVsoxdUCC0aSzBP/DKoNG19jN2Cy0g4Bf5/5/quSp37pvPswR8LV5rq8so3oQsCLd4O/72U3nwotjBVAr+ma0I6/Lh+tQGEjRaLdviaVeWeOQ7LxPAfU+DHv2JX+vVarGuwtii+HdvZ2diA5VF630Y9gh2X/wneQS0Q==)
    username: ENC(KNmR6xXVrBWWTx00IGy2bg==)
    password: ENC(ZPbMV1gg+HcQKuTG2IMrHfNof4RowN2nf3LQuIfElWY=)

host: ENC(tUCEL5GV2us7l71eJJxpAssj42SwWA1Wzw42CPKjnlI43VVWWoJuRA==)
mpQrCode: ENC(T5FrgRttE1NBj5j97TEhDAv2sg4/w7rfeV8F0YUz4V36XKFUSU4B6NJNR3kN23i3H6dHGJbs9Pk=)
templateId: ENC(DKej2S27UicnnbsxGmKthpoIQz9kekIal2h0OxqzQsfggGcfy163HSbgGtl27hWZfSaGQiE+YLg=)

wx:
  mp:
    app-id: ENC(NCAyTbnmpBhi+mMFIdFsybkOY//fMbomPOfLWwEausA=)
    secret: ENC(744TI4CgaAqoRZyGc5C7UsMvlOyS3zl8Qgv51g5AAbWINSnlIW9n4cF4gJCs24Kx)
logging:
  level:
    root: error
    com:
      godfunc: error
