spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/paopao?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

host: http://localhost # 服务host
mpQrCode: http://weixin.qq.com/r/xxxx # 微信公众号链接
templateId: 3XMYYC4jpz3nSWWVRehUK0oLBo7WN4A_6L56FlDVIUM # 消息模板id

wx:
  mp:
    app-id: 123
    secret: 345
log:
  path: /tmp