spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/paopao?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAEM}
    password: ${MYSQL_PASSWORD}

mpQrCode: ${MP_QR_CDOE} # 微信公众号链接
templateId: ${TEMPLATE_ID} # 消息模板id

wx:
  mp:
    app-id: ${WX_APP_ID} # 微信公众号appid
    secret: ${WX_SECRET}  # 微信公众号secret
log:
  path: /tmp